### ISSUE TITLE
Custom Mutator

### ISSUE THREAD

**Issue by Mem2019** [P1umer/AFLplusplus-Extractor#1]
It seems that after the shared library is compiled, the custom mutator that uses such library is missed. Will it be available? Thanks.

**Comment by P1umer** [comment]
Well, in order to distinguish the functionality and allow the shared library generated by the this extractor to be used in more places (not just a certain version of afl++, and even in the future it may not be afl++), I did not place the source of the custom mutator in this repo. But this should not be too difficult, just follow the documentation of the custom mutator at [https://aflplus.plus/docs/custom_mutators/ ↗](https://aflplus.plus/docs/custom_mutators/). I hope this helps you.

**Comment by Mem2019** [comment]
Thank you.
